### PR TITLE
Rewrite the ldapsync scripts for extensibility.

### PR DESCRIPTION
**Pull request by bzh-bzh**
Now the `google_groups` script inherits from a base class, which defines a `sync()` method, and adds common flags and logging options.

I also added a new flag to log to a log file.

I envision every app running as a separate cronjob, defined in puppet (or maybe one job, with lots of `&&`s). Since the script shouldn't make changes too often, I have everything output to stdout, and from there to cron email.

Tested, and runs successfully.

### CODE REVIEW

**Comment by dkess** [comment]
Thanks for working on this! These changes mostly look good. Syncing each service separately is a good idea.

I always imagined each group implementing `users_in_group` and `add_user` functions, and then having the default implementation of `sync` call those functions, since I expect the logic in the `sync` function will be repeated across each service.

Also, instead of running cronjobs in puppet, I think we should use Kubernetes cron for this, since then we don't have to worry about how to package the Python dependencies on supernova. It's also unclear which host this should run on anyways.

**Comment by bzh-bzh** [comment]
Can k8s cronjobs do logging and/or cron emails? Those are going to be pretty important I feel for this, so we have records of who got added. I agree that it's going to be a hassle to handle dependencies otherwise, though.

I agree that a lot of logic can be reused. I'm not sure if SYNC_PAIRS can be generalized though, we'll likely have to figure something else out for future apps.

**Comment by dkess** [comment]
`SYNC_PAIRS` is definitely tricky, I'm not happy with how it's done now, since I feel like that configuration should go in a file separate from the actual service implementations.

Re: emails, it's not ideal, but we could use ocflib's `send_problem_report` for errors on this. I don't think we should send emails for when this is operating normally-- I believe we can see modification logs in LDAP anyways, if we need to.

**Review by abizer — APPROVED** [review]
Use [stdin2syslog](https://github.com/ocf/utils/blob/master/staff/sys/stdin2syslog) to have this go syslog as well.

**Comment by bzh-bzh** [comment]
I'm going to merge this for now, and put revised configs and logging changes in separate PRs.

**Pull request merged**
